# Generated by Django 5.0.1 on 2024-04-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guidedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guidename', models.CharField(max_length=20)),
                ('Phonenumber', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Places_To_Visit', models.CharField(max_length=500)),
                ('Activities_To_Do', models.CharField(max_length=250)),
                ('Duration', models.CharField(max_length=50)),
                ('Transport_Details', models.CharField(max_length=100)),
                ('Food_Details', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
